[workspace]
members = [
  "01-calorie-counting/rust",
  "02-rock-paper-scissors/rust",
  "03-rucksack-reorganization/rust",
  "04-camp-cleanup/rust",
  "utils/rust",
  "cli",
]
default-members = [
  "cli"
]
