[package]
name = "sixteenth"
version = "0.1.0"
edition = "2021"
default-run = "sixteenth"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
sscanf = "0.4.0"
utils = { path = "../../utils/rust" }
