[package]
name = "seventeenth"
version = "0.1.0"
edition = "2021"
default-run = "seventeenth"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.13.1"
utils = { path = "../../utils/rust" }
