[package]
name = "eighteenth"
version = "0.1.0"
edition = "2021"
default-run = "eighteenth"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
utils = { path = "../../utils/rust" }
