[package]
name = "rucksack"
version = "0.1.0"
edition = "2021"
default-run = "rucksack"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../../utils/rust" }
